platform:ios, '6.0'
pod 'AFNetworking'
pod 'ReactiveCocoa'
pod 'REMenu'
pod 'ConciseKit'
pod 'MBProgressHUD'
pod 'RETableViewManager', :head
pod 'JSONModel'
pod 'SSKeychain'
pod 'hpple', '~> 0.2.0'
pod 'SparkInspector'